# Generated by Django 4.1.3 on 2022-12-19 06:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTorrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Sci-fi', 'Sci-fi'), ('Wholesome', 'Wholesome'), ('Comedy', 'Comedy')], max_length=9)),
                ('date_of_upload', models.DateTimeField(editable=False)),
                ('date_of_last_download', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
