# Generated by Django 4.1.3 on 2022-12-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetorrent',
            name='image_field',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='animetorrent',
            name='date_of_last_download',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
