# Generated by Django 4.1.3 on 2022-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animetorrent_image_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetorrent',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
